/*
 * deviceSelector.java
 *
 * Created on 6 octobre 2008, 12:35
 */

package UI;

import javax.sound.sampled.*;

/**
 *
 * @author  William
 */
public class deviceSelector extends javax.swing.JFrame {
    
    private mainFrame frm;
    
    /** Creates new form deviceSelector */
    public deviceSelector(mainFrame frm) {
        this.frm = frm;
        initComponents();
        Mixer.Info[] inf = AudioSystem.getMixerInfo();
        for (int x = 0; x < inf.length; x++) {
            if (inf[x].getDescription().toLowerCase().contains("capture")) {
                this.jComboBoxRecord.addItem(inf[x]);
                if (inf[x].hashCode() == frm.getRecorder().getMixerInfo().hashCode()) {
                    this.jComboBoxRecord.setSelectedItem(inf[x]);
                }
            } else {
                this.jComboBoxPlay.addItem(inf[x]);
                if (inf[x].hashCode() == frm.getPlayer().getMixerInfo().hashCode()) {
                    this.jComboBoxPlay.setSelectedItem(inf[x]);
                }
            }
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jComboBoxPlay = new javax.swing.JComboBox();
        jComboBoxRecord = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configuration audio");

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 14));
        jLabel1.setText("Sélectionnez les dispositifs d'enregistrement et de lecture de votre ordinateur.");
        jLabel1.setPreferredSize(new java.awt.Dimension(475, 40));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setText("Dispositif de lecture audio :");
        jPanel3.add(jLabel2);

        jLabel3.setText("Dispositif de capture audio :");
        jPanel3.add(jLabel3);

        jPanel1.add(jPanel3, java.awt.BorderLayout.WEST);

        jPanel4.setLayout(new java.awt.GridLayout(2, 1));

        jComboBoxPlay.setPreferredSize(new java.awt.Dimension(400, 20));
        jPanel4.add(jComboBoxPlay);

        jPanel4.add(jComboBoxRecord);

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        frm.setPlayer(AudioSystem.getMixer((Mixer.Info)this.jComboBoxPlay.getSelectedItem()));
        frm.getProps().setPlayerMixerNbr(this.jComboBoxPlay.getSelectedIndex());
        frm.setRecorder(AudioSystem.getMixer((Mixer.Info)this.jComboBoxRecord.getSelectedItem()));
        frm.getProps().setRecMixerNbr(this.jComboBoxRecord.getSelectedIndex());
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JComboBox jComboBoxPlay;
    private javax.swing.JComboBox jComboBoxRecord;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
    
}
