/*
 * HelpDialog.java
 *
 * Created on 2 décembre 2008, 19:41
 */

package UI;

import artificialcomposer.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  William
 */
public class HelpDialog extends javax.swing.JDialog {

    public static final int GENERAL_HELP = 0;
    public static final int TROUBLESHOOT = 1;
    public static final int AI_HELP = 2;
    
    // On met les ressources dans le dossier build/classes/theProj/ !
    
    public HelpDialog(java.awt.Frame parent, boolean modal, int type) {
        super(parent, modal);
        initComponents();
        this.jEditorPanePage.setText("Chargement...");
        java.net.URL page = null;
        switch (type) {
            case HelpDialog.GENERAL_HELP:
                page = Main.class.getResource("generalHelp.html");
                break;
            case HelpDialog.TROUBLESHOOT:
                page = Main.class.getResource("troubleshoot.html");
                break;
            case HelpDialog.AI_HELP:
                page = Main.class.getResource("reconIA.html");
                break;
            default:
                this.jEditorPanePage.setText("Fichier d'aide non présente pour cette section.\nDésolé...");
        }
        if (page != null) {
            try {
                this.jEditorPanePage.setPage(page);
                this.jEditorPanePage.setContentType("text/html; charset=UTF-8");
            } catch (IOException ex) {
                Logger.getLogger(HelpDialog.class.getName()).log(Level.SEVERE, null, ex);
                this.dispose();
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPanePage = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aide");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 400));
        jScrollPane1.setViewportView(jEditorPanePage);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jButtonClose.setText("Fermer");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
    this.dispose();
}//GEN-LAST:event_jButtonCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JEditorPane jEditorPanePage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
