/*
 * tessitureSel.java
 *
 * Created on 9 octobre 2008, 15:51
 */

package UI;

import javax.swing.JOptionPane;

/**
 *
 * @author  William
 */
public class tessitureSel extends javax.swing.JFrame {
    
    private mainFrame frm;
    
    /** Creates new form tessitureSel */
    public tessitureSel(mainFrame frm) {
        initComponents();
        this.frm = frm;
        this.jSpinnerHigh.setValue(frm.getProps().getTessitureHigh());
        this.jSpinnerLow.setValue(frm.getProps().getTessitureLow());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerHigh = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSpinnerLow = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sélection de tessiture");
        getContentPane().setLayout(new java.awt.BorderLayout(0, 6));

        jLabel1.setText("<html>Entrez les limites de tessiture (en hertz) de votre instrument de musique.<br /> Lors de l'analyse des enregistrement, les notes trouvées en dehors de l'intervalle défini par ces limites sont ignorées.</html>");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setPreferredSize(new java.awt.Dimension(559, 60));
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1, 0, 6));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Limite haute :");
        jPanel3.add(jLabel2, java.awt.BorderLayout.WEST);

        jSpinnerHigh.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel3.add(jSpinnerHigh, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Limite basse :");
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        jSpinnerLow.setPreferredSize(new java.awt.Dimension(60, 20));
        jPanel4.add(jSpinnerLow, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 2, 1));

        jButtonCancel.setText("Annuler");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        Number high = (Number)this.jSpinnerHigh.getValue();
        Number low = (Number)this.jSpinnerLow.getValue();
        if (high.intValue() > 0 && low.intValue() > 0) {
            if (high.intValue() > low.intValue()) {
                // Données valides.
                frm.setTessitureHigh(high.doubleValue());
                frm.getProps().setTessitureHigh(high.doubleValue());
                frm.setTessitureLow(low.doubleValue());
                frm.getProps().setTessitureLow(low.doubleValue());
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "La limite haute doit être plus grande que la limite basse.", "Erreur", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Données incorrectes. Tessiture non modifiée.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonOKActionPerformed
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSpinner jSpinnerHigh;
    private javax.swing.JSpinner jSpinnerLow;
    // End of variables declaration//GEN-END:variables
    
}
