/*
 * tuner.java
 *
 * Created on 9 octobre 2008, 17:15
 */

package UI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  William
 */
public class tuner extends javax.swing.JFrame {
    
    private mainFrame frm;
    private tunerThread tuneIt;
    
    /** Creates new form tuner */
    public tuner(mainFrame frm) {
        initComponents();
        this.frm = frm;
        tuneIt = new tunerThread(this);
        tuneIt.start();
    }
    
    public void showTune(double note) {
        // Sol# : 415.304hz.
	// Si b : 466.163hz.
        if (note <= 441.0 && note >= 439.2 || note <= 886.0 && note >= 878.4) {
            try {
                if (note > 600) note /= 2;
                // On admet qu'on est accordé...
                this.jProgressBarHigh.setValue(0);
                this.jProgressBarLow.setValue(0);
                this.jProgressBarHigh.setString("OK");
                this.jProgressBarLow.setString("OK");
                this.jProgressBarHigh.setStringPainted(true);
                this.jProgressBarLow.setStringPainted(true);
                Thread.sleep(2000);
                return;
            } catch (InterruptedException ex) {
                Logger.getLogger(tuner.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        int percent;
        this.jProgressBarHigh.setStringPainted(false);
        this.jProgressBarLow.setStringPainted(false);
        if (note >= 440) {
            // On est trop haut.
            this.jProgressBarLow.setValue(0);
            percent = (int)(((note - 440)/(466 - 440))*100);
            if (percent > 100) percent = 100;
            this.jProgressBarHigh.setValue(percent);
        } else {
            // On est trop bas.
            this.jProgressBarHigh.setValue(0);
            percent = (int)(((440 - note)/(440 - 415))*100);
            if (percent > 100) percent = 100;
            this.jProgressBarLow.setValue(percent);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelState = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jProgressBarHigh = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jProgressBarLow = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Accordeur");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabelState.setText("Initialisation...");
        getContentPane().add(jLabelState, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24));
        jLabel2.setText("#");
        jPanel3.add(jLabel2);
        jPanel3.add(jProgressBarHigh);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jLabel3.setFont(new java.awt.Font("SansSerif", 2, 24));
        jLabel3.setText("b");
        jPanel4.add(jLabel3);
        jPanel4.add(jProgressBarLow);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButtonClose.setText("Fermer");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonClose, java.awt.BorderLayout.CENTER);

        jLabel1.setText("Veuillez Maintenir la note jusqu'à stabilisation de l'accordeur.");
        jPanel2.add(jLabel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        tuneIt.setRunning(false);
        getFrm().setTunerActive(false);
    }//GEN-LAST:event_formWindowClosed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBarHigh;
    private javax.swing.JProgressBar jProgressBarLow;
    // End of variables declaration//GEN-END:variables

    public mainFrame getFrm() {
        return frm;
    }

    public void setFrm(mainFrame frm) {
        this.frm = frm;
    }

    public javax.swing.JLabel getJLabelState() {
        return jLabelState;
    }

    public void setJLabelState(javax.swing.JLabel jLabelState) {
        this.jLabelState = jLabelState;
    }
    
}
